import Head from "next/head";
import { useEffect,useState } from "react";

export default function ProfileUpdate () {
    const [screenHeight,setScreenHeight] = useState (0);

    useEffect(() => {
      setScreenHeight(window.innerHeight - 60);
    },[])

    return (
        <>
         <Head>
            <title>Talents Profile Update | Real Fast</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container } styles={{minheight:`${screenHeight}px`}}>
        <div className={styles.wrapper}>
            <h2 className={styles.title}>Update your Profile</h2>

            <form>
                <div className={styles.inputeBlockRow}>
                    <div className={styles.inputeBlock}>
                        <label className={styles.label}>first name</label>
                        <input
                        type="text" 
                        placeholder="first and middlename" 
                        className={styles.inputeField}>
                        </input>
                    </div>
                    <div className={styles.inputeBlock}>
                        <label className={styles.label}>last name</label>
                        <input
                        type="text" 
                        placeholder="surname" 
                        className={styles.inputeField}>
                        </input>
                    </div>
                </div>

                <div className={styles.inputeBlockMain}>
                        <label className={styles.label}>Phone number</label>
                        <input
                        type="text" 
                        placeholder="phone number" 
                        className={styles.inputeField}>
                        </input>
                    </div>
                    <div className={styles.inputeBlockMain}>
                        <label className={styles.label}>Address</label>
                        <input
                        type="text" 
                        placeholder="contact address" 
                        className={styles.inputeField}>
                        </input>
                    </div>

                <div className={styles.inputeBlockRow}>
                    <div className={styles.inputeBlock}>
                        <label className={styles.label}>Date of Birth</label>
                        <input
                        type="date" 
                        className={styles.inputeField}>
                        </input>
                    </div>
                    
                    <div className={styles.inputeBlock}>
                        <label className={styles.label}>gender</label>
                        <select className={styles.inputeField}>
                            <option value='Not specified '>Not specifide</option>
                            <option value='Male'>Male</option>
                            <option value='Female'>Female</option>
                        </select>
                    </div>
                </div>
                <button type="submit" className={styles.submitBtn}>Update Profile</button>
            </form>
        </div>
        </main>
        </>
    )
}

const styles = {
    container:'w-full h-screen flex flex-col justify-center items-center px-16',
    wrapper:'w-full md:w-[720px] py-8',
    title:'text-lg text-center mb-4',
    inputeBlockRow:'w-full flex flex-col md:flex-row md:gap-3 md:mb-4',
    inputeBlock:'w-full mb-4',
    inputeBlockMain:'w-full mb-4',
    label:'text-gray-500 mb-2',
    inputeField:'w-full block border border-gray-200 py-5 px-4 rounded-full text-gray-500',
    submitBtn:'w-full bg-indigo-800 py-5 px-4 rounded-full text-lg text-white',

}