import { useState,useEffect } from "react";
import Head from "next/head";
import Link from 'next/link';
import { RiBriefcase4Fill } from 'react-icons/ri'
import { AiFillFlag } from 'react-icons/ai'
import { db } from "@/settings/firebase/firebase.setup";
import { getDocs,collection,query,where } from "firebase/firestore";

export async function getStaticPaths() {
    const onSnap = await getDocs(collection(db,'jobs'));
    const paths = onSnap.docs.map(document => {
        return {
            params:{
                url:String(document.data().url)
            },
        }
    })

    return {
        paths,
        fallback:false
    }
}

export async function getStaticProps(context) {
    const pageUrl = context.params.url;

    const job = [];
    const q = query(collection(db,'jobs'),where('url','==',pageUrl));
    const onSnap = await getDocs(q);
    onSnap.docs.forEach(document => job.push(document.data()));

    return {
        props:{
            jobData:job[0]
        }
    }
}

export default function Job({jobData}) {
    const [screenHeight,setScreenHeight] = useState(0);

    useEffect(() => {
        setScreenHeight(window.innerHeight - 60);
    },[]);

    return (
        <>
      <Head>
            <title>Dashboard | Company</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>

        <main className='lg:grid' style={{minHeight:`${screenHeight}px`}}>
           
        </main>
        </>
    )
}

const styles = {
    container:'w-full flex flex-col justify-center items-center px-16',
}