import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ImUnderline } from "react-icons/im";



export default function ProfileUpdate () {
    // const [screenHeight,setScreenHeight] = useState (0);

    // useEffect(() => {
    //   setScreenHeight(window.innerHeight - 60);
    // },[])

    return (
        <>
         <Head>
            <title>Page title | Real Fast</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main>
            <div className={styles.container}>
                <div className={styles.jobBlock}>
                    <ul className={styles.jobSum}>
                        <li><b>Junior Full-Stack Devloper </b></li>
                        <li style={{ color:"purple" }}>Tractrac</li>
                        <li>Abuja</li>
                        <li>₦100,000 - ₦300,000 a month</li>
                        <button className={styles.jobApplybtn}><b>Apply now</b></button>
                    </ul>
                    
                </div>
                <div className={styles.jobDetail}>
                    <ul className={styles.detailBlock}>
                        <li><h1><b>Job details</b></h1></li>
                        <li  style={{ color:"grey" }}>No matching <Link href='#'>job preferences</Link></li>
                        <li>Salary</li>
                        <div className={styles.detailsPrice}>₦100,000 - ₦300,000 a month</div>
                        <li>Job Type</li>
                        <div className={styles.details}>Full-time</div>
                    </ul>
                </div>
                <div className={styles.jobDiscription}>
                    <ul className={styles.discriptionBlock}>
                        <li><h1><b>Title</b><span>:Junior Full-Stack Developer</span></h1></li>
                        <li><h1><b>Location</b><span>:Abuja</span></h1></li>
                        <li><h1><b>Application deadline</b><span>:22th may, 2023</span></h1></li>
                        <li><h1><b>Job Description:</b></h1></li>
                        <li>We are looking for a junior full-stack developer to join our team. The ideal candidate should have a strong understanding of web development and be comfortable working with both front-end and back-end technologies. The candidate should also have experience working with React for the front-end and Node.js for the back-end.</li>
                        
                        <ul className={styles.jobResposibilities}>
                        <h1><b>Job Description:</b></h1>
                            <li>He/She will develop and maintain web applications using React and Node.js</li>
                            <li>He/She will collaborate with cross-functional teams, including UI/UX designers, to design, develop, and implement new features.</li>
                            <li>He/She will write clean, maintainable, and efficient code.</li>
                            <li>He/She will Participate in code reviews to maintain code quality.</li>
                            <li>He/She will Debug and troubleshoot issues in the codebase.</li>
                            <li>He/She will Optimize applications for maximum speed and scalability.</li>
                            <li>He/she will stay up to date with emerging trends and technologies in web development.</li>
                        </ul>         
                        
                       <div className={styles.resposibilities}>
                            <ul className={styles.jobResposibilities}>
                                <h1><b>Requirements:</b></h1>
                                <li>Strong understanding of web development</li>
                                <li>Proficient in React and Node.js</li>
                                <li>Familiarity with CSS, HTML, and JavaScript</li>
                                <li>Understanding of RESTful APIs</li>
                                <li>Familiarity with version control systems (e.g. Git)</li>
                                <li>Experience with databases (e.g. MySQL, MongoDB)</li>
                                <li>Strong problem-solving skills</li>
                                <li>Excellent communication skills</li>
                                <li>Ability to work in a team environment.</li>
                            </ul>         
                                
                            <ul className={styles.jobResposibilities}>
                                <h1><b>Preferred qualifications:</b></h1>
                                <li>Bachelor's degree in Computer Science, Computer Engineering, or any related field<br/> or experience</li>
                                <li>Experience working with AWS or other cloud services.</li>
                                <li>Understanding of Agile methodologies</li>
                                <li>Experience working with UI/UX designers to create engaging user experiences.</li>
                            </ul>
                            <ul className={styles.howToApply}>
                                <h1><b>How to Apply</b></h1>
                                <li>Please send your resume, cover letter and Portfolio Link to Jobs@tractrac.co</li>
                                <li>Job Type: Full-time</li>
                                <li>Pay: ₦100,000.00 - ₦300,000.00 per month</li>
                                <li>Application Deadline: 16/05/2023</li>
                            </ul> 
                        </div>        
                        <button className={styles.reportJob}>Report job</button>
                    </ul>  
                </div>
            </div>
        </main>
        </>
    )
}

const styles = {
    container:'w-[700px] h-full flex flex-col items-center my-8 px-16 border border-solid shadow-md rounded-[7px]',
    jobBlock:'w-[800px] h-[300px] border border-solid  shadow-md rounded-[7px]',
    jobSum:'pt-[50px] pl-5 text-[25px]',
    jobApplybtn:'w-[200px] h-[50px] flex items-center justify-center my-4 bg-purple-700 rounded-[5px] text-[20px] text-white ',
    jobDetail:'flex items-center w-[800px] h-[250px] mt-4 border border-solid shadow-md rounded-[7px]',
    detailBlock:'pl-5 text-[20px] my-4',
    detailsPrice:'w-[270px] bg-gray-300 flex items-center justify-center rounded-[7px]',
    details:'w-[100px] bg-gray-300 flex items-center justify-center rounded-[7px]',
    jobDiscription:'flex items-center w-[800px] h-[1400px] mt-4 border border-solid shadow-md rounded-[7px]',
    discriptionBlock:'pl-5 text-[20px]',
    resposibilities:'w-[700px] bg-red-400',
    jobResposibilities:'pl-5 text-[20px] list-disc mt-4',
    howToApply:'py-4',
    reportJob:'w-[150px] h-[50px] flex items-center justify-center bg-gray-300 rounded-[5px] text-[20px] ',
}